package io.exhub.exhub_manager.pojo.DO;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IdentityAuthenticationDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public IdentityAuthenticationDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andFristNameIsNull() {
            addCriterion("frist_name is null");
            return (Criteria) this;
        }

        public Criteria andFristNameIsNotNull() {
            addCriterion("frist_name is not null");
            return (Criteria) this;
        }

        public Criteria andFristNameEqualTo(String value) {
            addCriterion("frist_name =", value, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameNotEqualTo(String value) {
            addCriterion("frist_name <>", value, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameGreaterThan(String value) {
            addCriterion("frist_name >", value, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameGreaterThanOrEqualTo(String value) {
            addCriterion("frist_name >=", value, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameLessThan(String value) {
            addCriterion("frist_name <", value, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameLessThanOrEqualTo(String value) {
            addCriterion("frist_name <=", value, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameLike(String value) {
            addCriterion("frist_name like", value, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameNotLike(String value) {
            addCriterion("frist_name not like", value, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameIn(List<String> values) {
            addCriterion("frist_name in", values, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameNotIn(List<String> values) {
            addCriterion("frist_name not in", values, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameBetween(String value1, String value2) {
            addCriterion("frist_name between", value1, value2, "fristName");
            return (Criteria) this;
        }

        public Criteria andFristNameNotBetween(String value1, String value2) {
            addCriterion("frist_name not between", value1, value2, "fristName");
            return (Criteria) this;
        }

        public Criteria andLastNameIsNull() {
            addCriterion("last_name is null");
            return (Criteria) this;
        }

        public Criteria andLastNameIsNotNull() {
            addCriterion("last_name is not null");
            return (Criteria) this;
        }

        public Criteria andLastNameEqualTo(String value) {
            addCriterion("last_name =", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotEqualTo(String value) {
            addCriterion("last_name <>", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameGreaterThan(String value) {
            addCriterion("last_name >", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameGreaterThanOrEqualTo(String value) {
            addCriterion("last_name >=", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLessThan(String value) {
            addCriterion("last_name <", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLessThanOrEqualTo(String value) {
            addCriterion("last_name <=", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameLike(String value) {
            addCriterion("last_name like", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotLike(String value) {
            addCriterion("last_name not like", value, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameIn(List<String> values) {
            addCriterion("last_name in", values, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotIn(List<String> values) {
            addCriterion("last_name not in", values, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameBetween(String value1, String value2) {
            addCriterion("last_name between", value1, value2, "lastName");
            return (Criteria) this;
        }

        public Criteria andLastNameNotBetween(String value1, String value2) {
            addCriterion("last_name not between", value1, value2, "lastName");
            return (Criteria) this;
        }

        public Criteria andCountryRegionIsNull() {
            addCriterion("country_region is null");
            return (Criteria) this;
        }

        public Criteria andCountryRegionIsNotNull() {
            addCriterion("country_region is not null");
            return (Criteria) this;
        }

        public Criteria andCountryRegionEqualTo(String value) {
            addCriterion("country_region =", value, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionNotEqualTo(String value) {
            addCriterion("country_region <>", value, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionGreaterThan(String value) {
            addCriterion("country_region >", value, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionGreaterThanOrEqualTo(String value) {
            addCriterion("country_region >=", value, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionLessThan(String value) {
            addCriterion("country_region <", value, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionLessThanOrEqualTo(String value) {
            addCriterion("country_region <=", value, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionLike(String value) {
            addCriterion("country_region like", value, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionNotLike(String value) {
            addCriterion("country_region not like", value, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionIn(List<String> values) {
            addCriterion("country_region in", values, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionNotIn(List<String> values) {
            addCriterion("country_region not in", values, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionBetween(String value1, String value2) {
            addCriterion("country_region between", value1, value2, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andCountryRegionNotBetween(String value1, String value2) {
            addCriterion("country_region not between", value1, value2, "countryRegion");
            return (Criteria) this;
        }

        public Criteria andIdTypeIsNull() {
            addCriterion("id_type is null");
            return (Criteria) this;
        }

        public Criteria andIdTypeIsNotNull() {
            addCriterion("id_type is not null");
            return (Criteria) this;
        }

        public Criteria andIdTypeEqualTo(Byte value) {
            addCriterion("id_type =", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotEqualTo(Byte value) {
            addCriterion("id_type <>", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeGreaterThan(Byte value) {
            addCriterion("id_type >", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("id_type >=", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLessThan(Byte value) {
            addCriterion("id_type <", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeLessThanOrEqualTo(Byte value) {
            addCriterion("id_type <=", value, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeIn(List<Byte> values) {
            addCriterion("id_type in", values, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotIn(List<Byte> values) {
            addCriterion("id_type not in", values, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeBetween(Byte value1, Byte value2) {
            addCriterion("id_type between", value1, value2, "idType");
            return (Criteria) this;
        }

        public Criteria andIdTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("id_type not between", value1, value2, "idType");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNull() {
            addCriterion("id_number is null");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNotNull() {
            addCriterion("id_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumberEqualTo(String value) {
            addCriterion("id_number =", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotEqualTo(String value) {
            addCriterion("id_number <>", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThan(String value) {
            addCriterion("id_number >", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("id_number >=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThan(String value) {
            addCriterion("id_number <", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThanOrEqualTo(String value) {
            addCriterion("id_number <=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLike(String value) {
            addCriterion("id_number like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotLike(String value) {
            addCriterion("id_number not like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberIn(List<String> values) {
            addCriterion("id_number in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotIn(List<String> values) {
            addCriterion("id_number not in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberBetween(String value1, String value2) {
            addCriterion("id_number between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotBetween(String value1, String value2) {
            addCriterion("id_number not between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andFacePhotoIsNull() {
            addCriterion("face_photo is null");
            return (Criteria) this;
        }

        public Criteria andFacePhotoIsNotNull() {
            addCriterion("face_photo is not null");
            return (Criteria) this;
        }

        public Criteria andFacePhotoEqualTo(String value) {
            addCriterion("face_photo =", value, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoNotEqualTo(String value) {
            addCriterion("face_photo <>", value, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoGreaterThan(String value) {
            addCriterion("face_photo >", value, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoGreaterThanOrEqualTo(String value) {
            addCriterion("face_photo >=", value, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoLessThan(String value) {
            addCriterion("face_photo <", value, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoLessThanOrEqualTo(String value) {
            addCriterion("face_photo <=", value, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoLike(String value) {
            addCriterion("face_photo like", value, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoNotLike(String value) {
            addCriterion("face_photo not like", value, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoIn(List<String> values) {
            addCriterion("face_photo in", values, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoNotIn(List<String> values) {
            addCriterion("face_photo not in", values, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoBetween(String value1, String value2) {
            addCriterion("face_photo between", value1, value2, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andFacePhotoNotBetween(String value1, String value2) {
            addCriterion("face_photo not between", value1, value2, "facePhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoIsNull() {
            addCriterion("back_photo is null");
            return (Criteria) this;
        }

        public Criteria andBackPhotoIsNotNull() {
            addCriterion("back_photo is not null");
            return (Criteria) this;
        }

        public Criteria andBackPhotoEqualTo(String value) {
            addCriterion("back_photo =", value, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoNotEqualTo(String value) {
            addCriterion("back_photo <>", value, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoGreaterThan(String value) {
            addCriterion("back_photo >", value, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("back_photo >=", value, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoLessThan(String value) {
            addCriterion("back_photo <", value, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoLessThanOrEqualTo(String value) {
            addCriterion("back_photo <=", value, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoLike(String value) {
            addCriterion("back_photo like", value, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoNotLike(String value) {
            addCriterion("back_photo not like", value, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoIn(List<String> values) {
            addCriterion("back_photo in", values, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoNotIn(List<String> values) {
            addCriterion("back_photo not in", values, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoBetween(String value1, String value2) {
            addCriterion("back_photo between", value1, value2, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andBackPhotoNotBetween(String value1, String value2) {
            addCriterion("back_photo not between", value1, value2, "backPhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoIsNull() {
            addCriterion("signature_photo is null");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoIsNotNull() {
            addCriterion("signature_photo is not null");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoEqualTo(String value) {
            addCriterion("signature_photo =", value, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoNotEqualTo(String value) {
            addCriterion("signature_photo <>", value, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoGreaterThan(String value) {
            addCriterion("signature_photo >", value, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoGreaterThanOrEqualTo(String value) {
            addCriterion("signature_photo >=", value, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoLessThan(String value) {
            addCriterion("signature_photo <", value, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoLessThanOrEqualTo(String value) {
            addCriterion("signature_photo <=", value, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoLike(String value) {
            addCriterion("signature_photo like", value, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoNotLike(String value) {
            addCriterion("signature_photo not like", value, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoIn(List<String> values) {
            addCriterion("signature_photo in", values, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoNotIn(List<String> values) {
            addCriterion("signature_photo not in", values, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoBetween(String value1, String value2) {
            addCriterion("signature_photo between", value1, value2, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andSignaturePhotoNotBetween(String value1, String value2) {
            addCriterion("signature_photo not between", value1, value2, "signaturePhoto");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andMessageIsNull() {
            addCriterion("message is null");
            return (Criteria) this;
        }

        public Criteria andMessageIsNotNull() {
            addCriterion("message is not null");
            return (Criteria) this;
        }

        public Criteria andMessageEqualTo(String value) {
            addCriterion("message =", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotEqualTo(String value) {
            addCriterion("message <>", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThan(String value) {
            addCriterion("message >", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThanOrEqualTo(String value) {
            addCriterion("message >=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThan(String value) {
            addCriterion("message <", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThanOrEqualTo(String value) {
            addCriterion("message <=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLike(String value) {
            addCriterion("message like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotLike(String value) {
            addCriterion("message not like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageIn(List<String> values) {
            addCriterion("message in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotIn(List<String> values) {
            addCriterion("message not in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageBetween(String value1, String value2) {
            addCriterion("message between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotBetween(String value1, String value2) {
            addCriterion("message not between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_identity_authentication
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 24 18:22:31 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_identity_authentication
     *
     * @mbg.generated Tue Jul 24 18:22:31 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}