package io.exhub.exhub_manager.pojo.DO;

import java.util.Date;

public class ManagerRoleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_role.id
     *
     * @mbg.generated Sat Aug 04 23:57:54 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_role.role_name
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_role.status
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_role.create_time
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_role.update_time
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_role.id
     *
     * @return the value of t_manager_role.id
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_role.id
     *
     * @param id the value for t_manager_role.id
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_role.role_name
     *
     * @return the value of t_manager_role.role_name
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_role.role_name
     *
     * @param roleName the value for t_manager_role.role_name
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_role.status
     *
     * @return the value of t_manager_role.status
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_role.status
     *
     * @param status the value for t_manager_role.status
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_role.create_time
     *
     * @return the value of t_manager_role.create_time
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_role.create_time
     *
     * @param createTime the value for t_manager_role.create_time
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_role.update_time
     *
     * @return the value of t_manager_role.update_time
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_role.update_time
     *
     * @param updateTime the value for t_manager_role.update_time
     *
     * @mbg.generated Sat Aug 04 23:57:55 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}