package io.exhub.exhub_manager.pojo.DO;

import java.util.Date;

public class ManagerModuleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_module.id
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_module.module_name
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    private String moduleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_module.module_url
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    private String moduleUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_module.parent_id
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_module.create_time
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_module.update_time
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_module.id
     *
     * @return the value of t_manager_module.id
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_module.id
     *
     * @param id the value for t_manager_module.id
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_module.module_name
     *
     * @return the value of t_manager_module.module_name
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_module.module_name
     *
     * @param moduleName the value for t_manager_module.module_name
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_module.module_url
     *
     * @return the value of t_manager_module.module_url
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_module.module_url
     *
     * @param moduleUrl the value for t_manager_module.module_url
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl == null ? null : moduleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_module.parent_id
     *
     * @return the value of t_manager_module.parent_id
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_module.parent_id
     *
     * @param parentId the value for t_manager_module.parent_id
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_module.create_time
     *
     * @return the value of t_manager_module.create_time
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_module.create_time
     *
     * @param createTime the value for t_manager_module.create_time
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_module.update_time
     *
     * @return the value of t_manager_module.update_time
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_module.update_time
     *
     * @param updateTime the value for t_manager_module.update_time
     *
     * @mbg.generated Thu Aug 02 22:04:25 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        return "ManagerModuleDO{" +
                "id=" + id +
                ", moduleName='" + moduleName + '\'' +
                ", moduleUrl='" + moduleUrl + '\'' +
                ", parentId=" + parentId +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
}