package io.exhub.exhub_manager.pojo.DO;

import java.util.Date;

public class PointRecordDO {

    public static final Byte REGIST = 0;
    public static final Byte REFFER = 1;
    public static final Byte AUTH = 2;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_record.id
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_record.referrer
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    private String referrer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_record.referral
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    private String referral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_record.type
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_record.point
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    private Long point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_record.create_time
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point_record.update_time
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_record.id
     *
     * @return the value of t_point_record.id
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_record.id
     *
     * @param id the value for t_point_record.id
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_record.referrer
     *
     * @return the value of t_point_record.referrer
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public String getReferrer() {
        return referrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_record.referrer
     *
     * @param referrer the value for t_point_record.referrer
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public void setReferrer(String referrer) {
        this.referrer = referrer == null ? null : referrer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_record.referral
     *
     * @return the value of t_point_record.referral
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public String getReferral() {
        return referral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_record.referral
     *
     * @param referral the value for t_point_record.referral
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public void setReferral(String referral) {
        this.referral = referral == null ? null : referral.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_record.type
     *
     * @return the value of t_point_record.type
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_record.type
     *
     * @param type the value for t_point_record.type
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_record.point
     *
     * @return the value of t_point_record.point
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public Long getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_record.point
     *
     * @param point the value for t_point_record.point
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public void setPoint(Long point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_record.create_time
     *
     * @return the value of t_point_record.create_time
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_record.create_time
     *
     * @param createTime the value for t_point_record.create_time
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point_record.update_time
     *
     * @return the value of t_point_record.update_time
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point_record.update_time
     *
     * @param updateTime the value for t_point_record.update_time
     *
     * @mbg.generated Fri Jul 27 11:08:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}